sys_unix.cpp: avoid namespace collision of file_handle in fcntl-linux.h
This broke the build:

    sys_unix.cpp:73:8: error: redefinition of ‘struct file_handle’
     struct file_handle {
	    ^
    In file included from /usr/include/bits/fcntl.h:61:0,
		     from /usr/include/fcntl.h:35,
		     from sysdeps.h:61,
		     from sys_unix.cpp:21:
    /usr/include/bits/fcntl-linux.h:311:8: error: previous definition of ‘struct file_handle’
     struct file_handle
	    ^
    sys_unix.cpp: In function ‘void SysMediaArrived(const char*, int)’:
    sys_unix.cpp:211:11: error: ‘struct file_handle’ has no member named ‘is_cdrom’
       if (fh->is_cdrom && type == MEDIA_CD) {
	       ^
    sys_unix.cpp:214:9: error: ‘struct file_handle’ has no member named ‘is_media_present’
	 fh->is_media_present = true;

Signed-off-by: Steven Noonan <steven@uplinklabs.net>