main_unix: use '1' instead of non-existent 'TRUE' macro
main_unix.cpp: In function ‘int main(int, char**)’:
main_unix.cpp:401:45: error: ‘TRUE’ was not declared in this scope
  setenv("SDL_VIDEO_ALLOW_SCREENSAVER", "1", TRUE);
                                             ^

Signed-off-by: Steven Noonan <steven@uplinklabs.net>